import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import styled from 'styled-components'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Raven Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/raven.png" />
      </Head>
	  <Sidebar />
	  <ChatPlaceholder>
		<Image src="/raven.png" alt="Raven" width={200} height={200} />
		<h1>Raven Chat</h1>
	  </ChatPlaceholder>
    </Container>
  )
}

const Container = styled.div`
	display: flex;
`;

const ChatPlaceholder = styled.div`
	flex: 1;
	height: 100vh;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	background-color: whitesmoke;
	::-webkit-scrollbar {
		display: none;
	}
	-ms-overflow-style: none;
	scrollbar-width: none;
	h1 {
		color: #3f0f40;
	}
`;
